version: '3.8'
services:
  snes-web:
    # A imagem agora vem do GitHub, já pronta e leve
    image: ghcr.io/cristhian-sancore/jogos-retro-online-web:main
    ports:
      - "5000:5000"
    volumes:
      - ./roms:/app/roms
      - ./data:/app/data
      - ./saves:/app/saves
      - ./covers:/app/static/covers
    environment:
      # Troque para o subdomínio que você vai configurar no Cloudflare Tunnel
      - NETPLAY_URL=wss://netplay.SEUDOMINIO.com.br/
    restart: unless-stopped
    depends_on:
      - netplay

  netplay:
    # A imagem compilada do Rust vem pronta do GitHub
    image: ghcr.io/cristhian-sancore/jogos-retro-online-netplay:main
    ports:
      - "3000:4000"
    restart: unless-stopped
